let lebar = 20.5 ;
let panjang = 30 ;
let harga = 1500000;
let ppn = 0.15;
let luas = lebar * panjang ;
let hasil = luas * harga ;
let pajak = hasil * ppn ;
let total = hasil + pajak ;
console.log('total harga yang harus dibayar =' + ' ' + total);